### ISSUE TITLE
Wrapper top-level component

### ISSUE THREAD

**Issue by mcupak** [ga4gh/ADA-M#16]
It would be useful if the top-level ADA-M components (header, profile, terms, metaconditions) were wrapped in a single component, e.g. `Adam`. This would allow upstream specifications to pull ADA-M in via a single field.

Compare with the consent code specification, e.g.:
- https://github.com/ga4gh/ga4gh-consent-policy/blob/develop/consent_code.yaml#L150
- https://github.com/ga4gh-beacon/specification/blob/develop/beacon.yaml#L364-L390

**Comment by mcupak** [comment]
@FrancisJMR WDYT?

**Comment by FrancisJMR** [comment]
Sorry I've been lagging behind on keeping up with all the recent mods.

That sounds like a good idea - a single top component to pull makes sense. I still have to test the OAS code.
