### ISSUE TITLE
matrixProfileUpdates should be an array

### ISSUE THREAD

**Issue by mcupak** [ga4gh/ADA-M#17]
[matrixProfileUpdates](https://github.com/ga4gh/ADA-M/blob/develop/adam.yaml#L37) field is defined as a pair, but it looks like it should be an array of pairs.

**Comment by sdelatorrep** [comment]
Hi @mcupak , I totally agree. In protobuf it was defined as:
```
repeated ProfileUpdates matrixProfileUpdates  = 5;
```
and
```
message ProfileUpdates {
    string date         = 1; // Date the change was made to the profile
    string description  = 2; // Text describing the profile change made
}
```
My mistake!

**Comment by FrancisJMR** [comment]
Yes, the basic version was just a pair to be updated, but to track changes over time it makes sense to change this to a list of pairs.
