### ISSUE TITLE
Is 1.0 specification finalized?

### ISSUE THREAD

**Issue by mcupak** [ga4gh/ADA-M#2]
Some of the fields contain notes asking questions, e.g. `// NOTE: Should there be multiple options for this, i.e., repeated?`. Is this specification finalized to a point that it can be integrated with upstream projects? If so, notes like this should be removed.

**Comment by FrancisJMR** [comment]
Notes have been removed. This version is compliant with the ADA-M v1.0 specifications.

**Comment by mcupak** [comment]
Perfect, thank you!
