### ISSUE TITLE
Reformat ADAM.proto

### ISSUE THREAD

**Issue by mcupak** [ga4gh/ADA-M#3]
The proto file uses some formatting rules that are not typical for proto files. It would be nice to conform to standard conventions, remove unnecessary whitespace, comments etc.

**Comment by FrancisJMR** [comment]
I've removed notes/comments but other descriptions have been left. Is there a convention to follow you can point me to?

**Comment by mcupak** [comment]
A good reference is the official style guide: https://developers.google.com/protocol-buffers/docs/style

And Google's existing code, e.g.: https://github.com/googleapis/googleapis/blob/master/google/datastore/v1/datastore.proto
